language: c
notifications:
 irc:
  channels: "anathema.us.nu#anathema"
  use_notice: true
  skip_join: true
env:
 global:
  - secure: "LeuOo7WkygCR9BDkBv8ttWqSvL0TcEVnEYArBHmkBRZijOvI3EqyFeJMVPKCHt5JWXUmuaUnbNdK8FzYGGoMDGp6XP9NrHpVKCfN+ok9uRf2HftBjzH5SgMSP0H/dkDo24hBtFjlK/MXB7iDqiig0D80iEsvTP/5kjiWXv39Niw="
addons:
 coverity_scan:
  project:
   name: "pjanouch/sensei-raw-ctl"
   description: "SteelSeries Sensei Raw control utility"
  notification_email: p.janouch@gmail.com
  build_command_prepend: "cmake .. -DCMAKE_BUILD_TYPE=Release"
  build_command: "make"
  branch_pattern: coverity_scan
compiler:
 - clang
 - gcc
before_install:
 - sudo apt-get update -qq
install:
 - sudo apt-get install -y help2man libusb-1.0-0-dev libgtk-3-dev
before_script:
 - mkdir build
 - cd build
script:
 - cmake .. -DCMAKE_INSTALL_PREFIX=/usr
 - make
 - cpack -G DEB
